### ISSUE TITLE
How to clone the docker with an existing data?

### ISSUE THREAD

**Issue by kyygit** [kartoza/docker-geoserver#120]
First, really appreciate this masterpiece. I am able to up a geoserver in less than 5 minutes (compared to few hours if i didn't use docker)

Now, I am able to use **docker volume** to create a store inside the geoserver, with the data files from my host. It works brilliant.

Next, I have a question. Assuming I have created a store (eg: a vector data shapefile is added), how do I share/clone this entire thing to my colleagues, such that he/she need not setup an empty geoserver again, but could immediately have all i have at the latest state?

**Comment by NyakudyaA** [comment]
> First, really appreciate this masterpiece. I am able to up a geoserver in less than 5 minutes (compared to few hours if i didn't use docker)
> 
> Now, I am able to use **docker volume** to create a store inside the geoserver, with the data files from my host. It works brilliant.
> 
> Next, I have a question. Assuming I have created a store (eg: a vector data shapefile is added), how do I share/clone this entire thing to my colleagues, such that he/she need not setup an empty geoserver again, but could immediately have all i have at the latest state?

If you are using docker volume you have two ways to get your friend on the same wavelength with you.

* run docker inspect your container and see where your volume is mounted from. 
ie docker inspect geoserver |grep volume
You can then copy the folder and share it with your friend
* Alternatively log in to the running container and copy the geoserver data directory and share the folder with your friend
 * When your friend spins up his running instance he should use a local geoserver data directory.

* Otherwise in production environments, you should ideally have all your data in a DB

**Comment by kyygit** [comment]
Thanks for your answer. 
I just realize, by copying the entire "/opt/geoserver/data_dir", it literally 'copy' everything :)

By the way, when you mention "... have all your data in a DB", do you mean postgis?

**Comment by NyakudyaA** [comment]
> Thanks for your answer.
> I just realize, by copying the entire "/opt/geoserver/data_dir", it literally 'copy' everything :)
> 
> By the way, when you mention "... have all your data in a DB", do you mean postgis?

Yes PostGIS or any other DB you are familiar with etc MySQL
