### ISSUE TITLE
Upgrade to GeoServer 2.9.x

### ISSUE THREAD

**Issue by shane-axiom** [kartoza/docker-geoserver#13]
GeoServer 2.9.x has been stable for a while now:

http://geoserver.org/release/stable/

GeoServer 2.9 appears to require Java 8:

http://docs.geoserver.org/stable/en/user/production/java.html

This will require a few small changes in the Dockerfile, including a change to use `FROM tomcat:8-jre8`.

Also, the current `master` state (Geoserver 2.8.2) should become a build on Docker Hub. I don't see any tags in the GitHub repo currently so I'm not sure how those are set up. Ideally I think Docker Hub should build all tags as images, and each GeoServer version should be tagged in the repo.

Once the release/tag pattern is clarified I can make a PR to upgrade to GeoServer 2.9.x.

**Comment by shane-axiom** [comment]
@timlinux Any opinions here? This image needs to stay current if it's going to be useful.

**Comment by timlinux** [comment]
Hi @shane-axiom 

I can take a look and build tagged versions. If you would like to make a PR with your desired changes that would also be welcomed.

**Comment by shane-axiom** [comment]
Thanks @timlinux. PR for GeoServer 2.9.1/Java 8 is here:

https://github.com/kartoza/docker-geoserver/pull/14

**Comment by shane-axiom** [comment]
@timlinux While you're looking into setting up automated Docker Hub builds for GitHub tags, could you build and tag a Docker Hub image for 2.9.1? The most current stable version is still 2.8.0:

https://hub.docker.com/r/kartoza/geoserver/tags/

**Comment by timlinux** [comment]
@shane-axiom there is a branch per stable version of GeoServer. Actually the branches generally include the bug fix release because often it is useful to deploy a known good configuration with specific versions. I've updated so that we have builds for all recent  stable versions:


<img width="1272" alt="screen shot 2017-10-17 at 22 07 30" src="https://user-images.githubusercontent.com/178003/31686867-d5eb7068-b387-11e7-8324-df85181ad75b.png">
