### ISSUE TITLE
Published docker images tag on DockerHub are not reproducible

### ISSUE THREAD

**Issue by tlvu** [kartoza/docker-geoserver#233]
See consequence in issue https://github.com/kartoza/docker-geoserver/issues/232 and especially comment https://github.com/kartoza/docker-geoserver/issues/232#issuecomment-808754831.

Need to re-release using a different tag so people are aware of it and to ensure reproducibility of already published tag.

Imagine someone already pulled 2.18.2, they will have no idea that what they have is not good anymore and have to pull again. Docker do not re-pull by default.

Or 2 persons having both 2.18.2, they will have no idea their version are in fact different ! This basically defeat the reproducibility of docker images.

If your existing tag keeps changing, then you have the exact same problems as the latest "moving" tag: https://vsupalov.com/docker-latest-tag/

I propose adding a "release" field to your docker tag, example how RPM packing does: https://www.thegeekdiary.com/understanding-rpm-versions-and-naming-schemes/ (DEB package have the very similar nomenclature also). So your tag will be like <geoserver_version>-<release_version>, ex: 2.18.2-20210326 or 2.18.2-r1.

Up to you to decide the format of your release_version. The goal is to make it visible there is a new build on existing version and to ensure reproducibility of past build.

**Comment by NyakudyaA** [comment]
@tlvu I usually publish the images as a once off activity and never release a newer version of the build but in this case there was no actual code changes to break functionality but improvements and fixing security vulnerabilities should be prioritized.

However to address your concern I think we just need to add test so that each PR is validated that it actually is building before being merged. This way we can ensure that nothing will break.

As for the tagging mechanism we need to think about this properly. Do we tag it to include the base image I.e
Kartoza/geoserver:2.18.2-tomcat9
Or another way. I am not in favor of different tags

@lucernae can we incorporate tests using GitHub workflows

**Comment by tlvu** [comment]
> As for the tagging mechanism we need to think about this properly. Do we tag it to include the base image I.e
> Kartoza/geoserver:2.18.2-tomcat9
> Or another way. I am not in favor of different tags

Well different release requires different tag.  Otherwise, how do you distinguish which release is which? How do you communicate there is a new release of the same original product version to fix security issue?

It is very common to have multiple releases on the same original product version.  RPM and DEB packages are very mature packaging format and they even enforce a "release version" on top of the "product version" to ensure new release are rolled out correctly and ensure reproducibility of previous releases (to track which machine did not receive the new release).

**Comment by lucernae** [comment]
Thank you for your feedback.

We definitely recognize and acknowledge this issue. These docker images were originally created for our own use case, so we dont think about that far yet at the beginning.

This is in our backlog, but our capacity is limited as we maintain these repo in pro-bono manner. So far, we tried to attempt to fix this issue gradually as we involved with projects that uses the repo. For example in https://github.com/kartoza/docker-postgis we are starting to include the release versioning in the tag.

**Comment by tlvu** [comment]
> we maintain these repo in pro-bono manner

Just want to say thanks again for this.  We understand the challenge, being a non-profit organization ourself.

You guys did a really good job, like already said in this PR https://github.com/kartoza/docker-geoserver/pull/230 "Also just would like to say thanks for maintaining this. We upgraded from 2.9.3 to 2.18.2 and it feels like a massive improvements, see https://github.com/bird-house/birdhouse-deploy/pull/136".

**Comment by lucernae** [comment]
@tlvu , if you are interested, can you give feedback/suggestion in this GitHub thread:

https://github.com/kartoza/docker-geonode/discussions/6

We are trying to draft a more generic approach for these docker images (the issue about the tagging is one of our longest pain point). We open this discussion there because GeoNode is our most heavily customized images and it's getting confusing to manage them without a deterministic build and image tag.

We linked the draft procedures there to gather feedback in case we miss anything. So your suggestions may affect how we manage this in the future. Because eventually we are going to apply the same procedures in this repo as well and it is quite a significant git directory structure overhauls.

**Comment by NyakudyaA** [comment]
With the introduction of tests and workflows things should be better and we can keep on adding , will close this and open a new one
