### ISSUE TITLE
HTTPS port hardcoded into tomcat configuration

### ISSUE THREAD

**Issue by pkExec** [kartoza/docker-geoserver#376]
I assumed by using the .env variable HTTPS_PORT I could set up where tomcat listened for https, but that's not the case; Tomcat always listens for port 8443.

**Comment by NyakudyaA** [comment]
> I assumed by using the .env variable HTTPS_PORT I could set up where tomcat listened for https, but that's not the case; Tomcat always listens for port 8443.

That is because that port needs to be opened in the context of the image https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L66. If you need to change it you have to build your own custom image using the build args. 

Example:
```
docker build --build-arg HTTPS_PORT=8443

```
Then you can use the port you have specified. There is no way to expose the port once the image has been built and we cannot expose a range of ports for security reasons
