### ISSUE TITLE
Database connections unclear

### ISSUE THREAD

**Issue by urzds** [kartoza/docker-geoserver#39]
It is unclear to us, how in `docker-compose.yml`, geoserver is made aware of the postgis database. For geogig, I can see that `PGHOST=geogig-db` is provided in `geogig.env`, but I am missing a similar configuration option for geoserver. How does this work? What is the default configuration and where is it set? Especially: How can I point geoserver at another database?

And finally: How does backup of all databases work? Do I need to setup a `dbbackups` container for each database? Currently `docker-compose.yml` seems to only provide backups for geoserver's database, but not for geogig's database.

**Comment by urzds** [comment]
So *geoserver* only depends on the *db* container, if the user manually creates such a setup using the interactive web-interface after starting the geoserver? Otherwise it runs without a backing postgis database?

If I want *geoserver* to use the *geogig* container, I need to manually set this up using the interactive web-interface?

How does *geogig* know that it shall track the changes in the *db* container, if the only information I give it is `PGHOST=geogis-db`, i.e. the address of the *geogig-db* container?

Since this appears to involve a lot of interactive configuration using the web-interface of geoserver: Is it possible to automatically set this up on container startup, i.e. in an `entrypoint.sh` script? This way I could automatically deploy these containers on our infrastructure.

**Comment by NyakudyaA** [comment]
@urzds https://github.com/kartoza/docker-geoserver/blob/master/docker-compose.yml#L36 specifies that geoserver depends on `db` and `geogig-db` - This implies that these two different databases can be accessed as a Geoserver store.
`db` will be a postgresql store
`geogig-db` will be a geogig store.
In order to use these store you need to set them up as per Geoserver documentation.

In order to version the db under geogig you need to do it within the **geogig container**. After running the docker-compose you run:
```
docker exec -it dockergeoserver_geogig_1 bash
geogig --repo "postgresql://geogig-db/gis/public/gis?user=docker&password=docker" pg import --all --host db --port 5432 --database gis --user docker --password docker
# This will import all tables in `db` to be under version control and you can then publish them in Geoserver as a Geogig store
```
I do not think that you need an entry point for this as Geoserver has a REST API which you can use to publish stores and publish data within the stores.

**NB**: The only current limitation we need to overcome is logging into the geogig container so that we can run the geogig commands. This we can overcome by using makefiles

**Comment by urzds** [comment]
Thanks for this thorough explanation!

I would suggest to automate the initial setup further, by creating an entrypoint script that sets up the geogig and/or raw postgis stores (possibly triggered by an environment variable) to ease usage of these containers outside of a local development environment, but I understand you have reasons against doing that.
