### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by gutleber** [kartoza/docker-geoserver#425]
building last version failed on libgdal-java
exit code: 100
The following packages have unmet dependencies:
  libgdal26 : Depends: libarmadillo9 (>= 1:9.200.7+dfsg) but it is not installable
              Depends: libcfitsio7 (>= 3.450~) but it is not installable
              Depends: libdap25 but it is not installable
              Depends: libjson-c3 (>= 0.11) but it is not installable
              Depends: libnetcdf13 (>= 1:4.0.0) but it is not installable
              Depends: libpoppler82 (>= 0.71.0) but it is not installable
              Depends: libqhull7 but it is not installable
Unable to correct problems, you have held broken packages.

How can I resolve this issue?

**Comment by NyakudyaA** [comment]
Are you building this manually? Are you using master or develop branch

**Comment by gutleber** [comment]
"docker-compose -f docker-compose-build.yml up -d --build" also end with same result

**Comment by NyakudyaA** [comment]
I have a feeling the PPA we use might have also been updated to remove libgdal. If that's the case we might have to try another PPA or alternatively downgrade to use a lower version of gdal. This issue of dropping the java bindings is discussed on various platforms i.e https://trac.osgeo.org/osgeolive/ticket/2288

**Comment by NyakudyaA** [comment]
I tried building this and it worked. Are you not able to pull the image from the docker hub repository? Otherwise you will need to checkout commit https://github.com/kartoza/docker-geoserver/commit/162c562d0cec6eeec1db30ba879a52a45c4ef0b5

**Comment by zacharlie** [comment]
I managed to get the build running on Windows 10 21H2 pretty simply on the master branch. I think this is a local environment configuration issue. GDAL and Windows can have issues though. I default to using conda when I work with gdal. I used the following commands to set up a fresh instance:

```pwsh
git clone https://github.com/kartoza/docker-geoserver.git
cd docker-geoserver
conda create -n geoserver-build -c conda-forge python gdal
conda activate geoserver-build
```

Then I get the active JAVA_HOME path from powershell (you can use `(get-command java).Source`, but I figure the shortpath for java is safer because "Program Files" including whitespace has never really made sense).

```pwsh
(New-Object -ComObject Scripting.FileSystemObject).GetFile((get-command java).Source).ShortPath
```

I of course had conda and java installed on the host machine beforehand as well. For me the java home path is `C:/PROGRA~1/Java/JDK-15~1.2/bin/java.exe`. I changed all the backslashes to forward slashes to avoid path issues. Then I set the `JAVA_HOME` variable in the default `.env` and ran the build and run commands separately:

```pwsh
docker-compose -f docker-compose-build.yml build --force-rm --no-cache
docker-compose -f docker-compose-build.yml up -d
```

Then I had no problems accessing http://127.0.0.1:8600/geoserver/

Closing as `works on my machine`. @gutleber I would suggest trying with gdal in a conda envirnonment (and using the conda-forge channel) when running the build...

**Comment by NyakudyaA** [comment]
@zacharlie Maybe you could add these build instructions to the readme. It would help a lot of people on windows
