### ISSUE TITLE
EXISTING_DATA_DIR Unclear

### ISSUE THREAD

**Issue by calebjohnson221** [kartoza/docker-geoserver#457]
Setting EXISTING_DATA_DIR=false has the same result as setting it to true - both values cause the password update script to be skipped. It is clear from the [Docker documentation](https://hub.docker.com/r/kartoza/geoserver) that setting it to true would do this, but it is not clear that setting it to **any** value is equivalent to setting it to true. This caused some confusion for us until I dug into the source code and found that its really just looking for any value in the env var. I see that the readme explains this a little better, mentioning just "setting" and "unsetting" the env var.

**Comment by NyakudyaA** [comment]
The condition `if [[ -z "${EXISTING_DATA_DIR}" ]]; then` basically implies that setting it to any value will cause it to be skipped. The solution here would be
* Update the documentation to mention that if the password to be updated then ${EXISTING_DATA_DIR} needs to be unset (default behaviour) otherwise any value set will make it being skipped
