### ISSUE TITLE
The plugin 'libjpeg-turbo' for geoserver2.25.2 doesn't work

### ISSUE THREAD

**Issue by rockychen-dpaw** [kartoza/docker-geoserver#673]
### What is the bug or the crash?

The version of the libjpeg installed in the image is 3.0.3  which doesn't match the version required by the plugin 'libjpeg-turbo' for geoserver2.25.2.
The java wrapper used by the plugin is  "JNI LibJPEGTurbo Wrapper Version: 1.2.1.5" which can support the version of the libjped up to 2.1.5.1

### Steps to reproduce the issue

1. login to geoserver
2. open the page "Tile Layers"
3. choose one wmts layer, and preview with format "jpeg"
4. an exception will be thrown in geoserver and also returned to browser.

### Versions

GeoServer Version: 2.25.2

**Comment by NyakudyaA** [comment]
@rockychen-dpaw There has been a lot of discussion about this issue and this has led to various improvements i.e https://github.com/kartoza/docker-geoserver/issues/653, if however downgrading the version being installed makes jpeg work, you can do a PR and we can test/merge. The issue here is that the GeoServer team also think that the `libjpeg-turbo` might not have the same benefits as before but they still need to conduct rigorous test to determine this and then take action
